

-- Design at least 10 SQL queries for suitable database application
-- using SQL DML statements: Insert, Select, Update, Delete with operators,
-- functions, and set operator.

SHOW DATABASES;
CREATE DATABASE LAB;
USE LAB;

CREATE TABLE EMPLOYEE(
EMP_NO INT PRIMARY KEY,
EMP_NAME VARCHAR(20),
DATE DATE,
POSITION VARCHAR(20)
);
desc EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1,"INDER",'2023-10-1',"EMP");
INSERT INTO EMPLOYEE VALUES(2,"KUNAL",'2023-10-10',"TL");
INSERT INTO EMPLOYEE VALUES(3,"ADI",'2023-10-15',"MANG");
INSERT INTO EMPLOYEE VALUES(4,"LOL",'2023-10-17',"CLERK");
INSERT INTO EMPLOYEE VALUES(5,"IND",'2023-10-20',"TL");

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET POSITION="MANG" WHERE EMP_NO=1;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_NO=5;

SELECT * FROM EMPLOYEE;

CREATE TABLE EMP(
EMP_NO INT PRIMARY KEY,
EMP_NAME VARCHAR(20),
DATE DATE,
SALARY INT 
);
desc EMPLOYEE;
INSERT INTO EMP VALUES(1,"INDER",'2023-10-1',50000);
INSERT INTO EMP VALUES(2,"KUNAL",'2023-10-10',15000);
INSERT INTO EMP VALUES(3,"ADI",'2023-10-15',25000);
INSERT INTO EMP VALUES(4,"LOL",'2023-10-17',45000);

SELECT * FROM EMP;

SELECT AVG(SALARY) FROM EMP;

SELECT CONCAT(EMP_NO,EMP_NAME) FROM EMP WHERE SALARY=50000;	

SELECT CONCAT(EMP_NO,EMP_NAME) FROM EMP WHERE SALARY IN (SELECT MAX(SALARY) FROM EMP);
SELECT UPPER(CONCAT(EMP_NAME)) FROM EMP WHERE SALARY=50000;
SELECT LOWER(CONCAT(EMP_NAME)) FROM EMP WHERE SALARY=50000;

SELECT * FROM EMP WHERE YEAR(DATE)='2023';
SELECT * FROM EMP WHERE MONTH(DATE)='11';

INSERT INTO EMP VALUES(5,"KUNBER",'2022-10-17',55000);

SELECT * FROM EMP WHERE EMP_NAME LIKE "KUN%";

SELECT * FROM EMP WHERE EMP_NO IN('1','2','5');

SELECT * FROM EMP WHERE EMP_NO NOT IN('1','2','5');

SELECT * FROM EMP WHERE YEAR(DATE) BETWEEN '2022' AND '2023'; 


