SHOW DATABASES;

USE library;

CREATE TABLE EMPL(
ID INT PRIMARY KEY,
NAME VARCHAR(250),
SALARY INT,
DEPT_ID INT
);

INSERT INTO EMPL VALUES(1,"MAX",10000,1);
INSERT INTO EMPL VALUES(2,"MARK",10000,3);
INSERT INTO EMPL VALUES(3,"ALICE",10000,4);
INSERT INTO EMPL VALUES(4,"JACK",70000,2);
INSERT INTO EMPL VALUES(5,"KAITH",80000,3);

UPDATE EMPL SET SALARY=450000 WHERE ID=3;
UPDATE EMPL SET SALARY=250000 WHERE ID=2;

SELECT * FROM EMPL;

CREATE INDEX SALARY_INDEX ON EMPL (SALARY);

-- OPERATION ON INDEX
SELECT * FROM EMPL WHERE SALARY<60000;              -- Select Records Using the Index:
EXPLAIN SELECT * FROM EMPL WHERE SALARY <90000;     -- Explain Query Execution Plan:
SELECT * FROM EMPL ORDER BY SALARY DESC;            --  Sort Records Using the Index:
UPDATE EMPL SET SALARY=45000 WHERE ID=3;             --  Update Records Using the Index:
UPDATE EMPL SET SALARY=SALARY*2 WHERE ID=1;

SELECT * FROM EMPL;
