-- left join

use lab;

CREATE TABLE CUSTOMERS(
CUST_ID INT PRIMARY KEY,
NAME VARCHAR(29)
);

CREATE TABLE ORDERSS(
ORDER_ID INT PRIMARY KEY,
CUST_ID INT
);
INSERT INTO CUSTOMERS VALUES(1,"ALEX");
INSERT INTO CUSTOMERS VALUES(2,"MARK");

INSERT INTO ORDERSS VALUES(101,1);
INSERT INTO ORDERSS VALUES(102,1);
INSERT INTO ORDERSS VALUES(103,2);

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERSS;

SELECT CUSTOMERS.CUST_ID,ORDERSS.ORDER_ID FROM CUSTOMERS LEFT JOIN ORDERSS ON CUSTOMERS.CUST_ID=ORDERSS.CUST_ID;