
use lab;

CREATE TABLE CUS(
CID INT PRIMARY KEY,
CNAME VARCHAR(20)
);

CREATE TABLE ORD(
OID INT,
PRICE INT,
CID INT,
FOREIGN KEY (CID) REFERENCES CUS(CID)
);

INSERT INTO CUS VALUES(1,"VINOD");
INSERT INTO CUS VALUES(2,"KING");
INSERT INTO CUS VALUES(3,"VIRAT");
INSERT INTO CUS VALUES(4,"IYER");

INSERT INTO ORD VALUES(101,1500,2);
INSERT INTO ORD VALUES(102,5000,1);
INSERT INTO ORD VALUES(103,8500,2);
INSERT INTO ORD VALUES(104,1700,3);
INSERT INTO ORD VALUES(105,1800,3);


SELECT CUS.CID,CNAME,PRICE FROM CUS RIGHT JOIN ORD ON CUS.CID=ORD.CID;  -- RIGHT JOIN QUERY