show databases;

use mysql;

CREATE TABLE CUSTOMERS(
CID INT PRIMARY KEY,
CNAME VARCHAR(20)
);

CREATE TABLE ORDERS(
OID INT,
OAMOUNT INT,
CID INT,
FOREIGN KEY (CID) REFERENCES CUSTOMERS(CID)
);

INSERT INTO CUSTOMERS VALUES(1,"VINOD");
INSERT INTO CUSTOMERS VALUES(2,"KING");
INSERT INTO CUSTOMERS VALUES(3,"VIRAT");
INSERT INTO CUSTOMERS VALUES(5,"IYER");

INSERT INTO ORDERS VALUES(1,150,1);
INSERT INTO ORDERS VALUES(2,50,2);
INSERT INTO ORDERS VALUES(3,85,1);
INSERT INTO ORDERS VALUES(4,170,3);

SELECT * FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.CID=ORDERS.CID;    --  JOIN QUERY/INNER JOIN THEY ARE SAME
