use lab;

CREATE TABLE COLORS(
COLOR VARCHAR(10)
);

CREATE TABLE SIZES(
SIZE VARCHAR(10)
);

INSERT INTO COLORS VALUES("RED");
INSERT INTO COLORS VALUES("BLUE");
INSERT INTO COLORS VALUES("ORANGE");


INSERT INTO SIZES VALUES("SMALL");
INSERT INTO SIZES VALUES("MEDIUM");
INSERT INTO SIZES VALUES("LARGE");
INSERT INTO SIZES VALUES("XL");

SELECT COLORS.COLOR,SIZES.SIZE FROM COLORS CROSS JOIN SIZES;